### ISSUE TITLE
Failed to load tsconfig.json: Missing baseUrl in compilerOptions

### ISSUE THREAD

**Issue by khuong291** [gitname/react-gh-pages#1]
Hi, I create my react app using this:

`create-react-app my-app --scripts-version=react-scripts-ts`

When I run `yarn deploy` I got this error:

```
yarn run v1.3.2
$ npm run build

> khuong_website@0.1.0 build /Users/khuongpham/WebFrontEnd/khuong_website
> react-scripts-ts build

Failed to load tsconfig.json: Missing baseUrl in compilerOptions
Creating an optimized production build...
Found no baseUrl in tsconfig.json, not applying tsconfig-paths-webpack-plugin
Found no baseUrl in tsconfig.json, not applying tsconfig-paths-webpack-plugin
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
ts-loader: Using typescript@2.8.1 and /Users/khuongpham/WebFrontEnd/khuong_website/tsconfig.json
Compiled successfully.

File sizes after gzip:

  35.45 KB  build/static/js/main.60e3476d.js
  300 B     build/static/css/main.29266132.css

The project was built assuming it is hosted at https://khuong.github.io.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

$ gh-pages -b master -d build
Cloning into 'node_modules/gh-pages/.cache/aHR0cHM6Ly9naXRodWIuY29tL2todW9uZzI5MS9raHVvbmdfd2Vic2l0ZS5naXQ'...
remote: Repository not found.
fatal: repository 'https://github.com/khuong291/khuong_website.git/' not found

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here is my `package.json` look like:

```
{
  "name": "khuong_website",
  "version": "0.1.0",
  "private": true,
  "homepage": "https://khuong.github.io",
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts-ts": "2.14.0"
  },
  "scripts": {
    "predeploy": "npm run build",
    "deploy": "gh-pages -b master -d build",
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/jest": "^22.2.2",
    "@types/node": "^9.6.1",
    "@types/react": "^16.1.0",
    "@types/react-dom": "^16.0.4",
    "gh-pages": "^1.1.0",
    "typescript": "^2.8.1"
  }
}

```

And my `tsconfig.json`:

```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "baseUrl": ".",
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}

```

**Comment by gitname** [comment]
Hi @khuong291,

Thanks for including so much relevant information in your Issue report.

My analysis of your situation is below. Please note that I have never used TypeScript before, so I may be overlooking something. I used a generic troubleshooting process in this analysis.

1. Regarding the message: `Failed to load tsconfig.json: Missing baseUrl in compilerOptions`

    In the `tsconfig.json` file you provided, the `baseUrl` property is, indeed, not located inside the `compilerOptions` property. I think the message above is reporting that fact.

    I recommend you put a `baseUrl` property inside the `compilerOptions` property, like this:

    ```diff
      {
        "compilerOptions": {
    +     "baseUrl": ".",
          "outDir": "build/dist",
           //...
    ```

    I don't mean to imply that `"."` is the correct value for that property (I am not familiar with that property, as I have never used TypeScript before).

2. Regarding the message: `The project was built assuming it is hosted at https://khuong.github.io.`

    I see your GitHub username as being `khuong291`, not `khuong`. Because of that, I think your app will be hosted at `https://khuong291.github.io`, not at `https://khuong.github.io`.

    I recommend you change the `homepage` property in `package.json` accordingly, like this:

    ```diff
     {
       "name": "khuong_website",
       "version": "0.1.0",
       "private": true,
    -  "homepage": "https://khuong.github.io",
    +  "homepage": "https://khuong291.github.io",
    ```

    For more information, I recommend you read this [GitHub Help article](https://help.github.com/articles/user-organization-and-project-pages/) about the URLs that GitHub assigns to User Pages sites vs. Project Pages sites.

3. Regarding the message: `fatal: repository 'https://github.com/khuong291/khuong_website.git/' not found`

    I recommend you verify that that repository exists. When I visit that URL, I don't see a repository homepage; instead, I see an Error 404 page (shown below). To me, that means the repository is either private (which is OK), or it doesn't exist at all.

    ![image](https://user-images.githubusercontent.com/7143133/38099294-149384be-332f-11e8-9efc-9cd51e3a8fff.png)

4. The URL in Item 3 does not appear to me to be consistent with the `"homepage"` property in the `package.json` file you provided.

    If your GitHub username is `khuong291` and the name of your repository on GitHub is `khuong_website`, I recommend you define `"homepage"` to be: `"https://khuong291.github.io/khuong_website"`.

**Comment by khuong291** [comment]
Thank you so much, it works 👍
