### ISSUE TITLE
"git-upload-pack" command not found with React v16.4.2

### ISSUE THREAD

**Issue by drewkiimon** [gitname/react-gh-pages#10]
For some reason, once in a blue moon I won't be able to run **npm run deploy** because when attempting to do "gh-pages -d build" it cannot find git-upload-pack. If I give it a day or two, then come back and try to deploy it works perfectly. 

Is there a fix to this? Not sure how to push my React project to github pages when it keeps giving me these errors.

![git upload pack](https://user-images.githubusercontent.com/16771352/44271510-297b4400-a1ef-11e8-8728-97d5171ea2db.PNG)

Edit: 8-17-18 @ 1 PM
It seems that my old projects running React v16.4.1 upload perfectly fine. However, my most recent project is using React v16.4.2. Anyone sure if that could be the reason why it isn't working?

**Comment by gitname** [comment]
Hi @drewkiimon,

I'll paste the error message here to facilitate future searches through this repo's issues:
```
git-upload-pack '.': git-upload-pack: command not found
```

I don't recall having seen that error message before.

I interpret the error message to mean whatever _thing_ happens to be looking for a command named `git-upload-pack` is not finding one in the context in which it is looking for it. That's about all I have gleaned from the combination of information you provided and my own knowledge.

---

My thoughts:

* I think one way to find out what that _thing_ is that is looking for that command, is to dig into the `gh-pages -d build` invocation and trace the execution flow. In other words, view the contents of `C:\Users\pagana2\Documents\code\eversnake\node_modules\.bin\gh-pages` (which is a bash script) and step through each instruction until you see something looking for the `git-upload-pack` command. I have not done this, myself, as it sounds pretty tedious to me!

* Assuming the _thing_ is your shell, I am curious what the output of `$ which git-upload-pack` is, both when the deployment process is working and when the deployment process is not working.

    For reference, here is what `$ which git-upload-pack` outputs on my Windows system running *Git bash* inside ConEmu:

    ```
    $ which git-upload-pack
    /mingw64/bin/git-upload-pack
    ```

* I haven't tested this deployment process with React v16.4.2 yet. I'll put that on my todo list.

    * [ ] Test this deployment process with React v16.4.2.

**Comment by drewkiimon** [comment]
@dangpro-1210  @gitname It turns out that since I'm using CMDER it uses it's own pre-installed version of Git. I had to reinstall git, add the path to git-upload-pack, and then restart my computer to get it to work.

It's just weird since it worked in the past and I could see my React projects online.

**Comment by alamgirqazi** [comment]
I have the same error with all consoles. VS Code Integrated Terminal, Hyper and CMDER. 

`git-upload-pack '.': git-upload-pack: command not found
fatal: Could not read from remote repository.`

**Comment by dangpro-1210** [comment]
As @drewkiimon said, if it doesn't work, it 'cause the git it self. So the way to fix it is to reinstall it and add the git-upload-pack's path.

**Comment by ieopvl** [comment]
Hi, if you want resolve this mistake without efforts just try to do "npm run deploy" from git bash (not from cmder windows terminal)

**Comment by khang-nd** [comment]
Thank you @ieopvl, your solution worked for me.

**Comment by Noxormy** [comment]
Thank you @ieopvl

**Comment by rajeev-sirpi** [comment]
Thanks @khang-nd , worked

**Comment by prateek-works** [comment]
thankyou so so much @ieopvl . You're a savior.

**Comment by jperalta-EndlessCodeStudio** [comment]
@ieopvl Thanks dude.

**Comment by yervand-stepanyan** [comment]
@ieopvl Thank you, running "**npm run deploy**" from "**git bash terminal**" works for **React v17.0.1**, too.

**Comment by Tiffolin** [comment]
@ieopvl  my luscious head of hair thanks you, (since I no longer have to spend hours pulling them out figuring how to 'fix' this)

**Comment by drewkiimon** [comment]
Seems like things have been sorted out!

**Comment by danya-prohvat** [comment]
Thanks

**Comment by davitSahakyan** [comment]
@ieopvl thank you it worked
