### ISSUE TITLE
"homepage" key in package.json does not work with react-i18next

### ISSUE THREAD

**Issue by sandro-mueller** [gitname/react-gh-pages#101]
When adding the homepage key inside the `package.json` while working with `react-i18next`, the whole app stops being translated.

**To reproduce**

```json
"i18next": "^21.8.8",
"react": "^18.1.0",
"react-i18next": "^11.17.0",
"react-i18next": "^11.17.0",
```

**i18n config**

```js
i18n
  .use(initReactI18next)
  .use(HttpApi)
  .init({
      fallbackLng: {
      default: ['en'],
     },
    debug: true,
   })
```

**Comment by gitname** [comment]
Hi @Motion4Life, I am not familiar with the `react-i18next` package. You might try starting from "scratch" (i.e. no app), following the steps in the tutorial, deploying the app to GitHub Pages, then adding in the `react-i18next` package.

On a side note, I noticed in your post above, `react-i18next` is listed as a dependency twice. I have never tried listing a package twice in the `package.json` file. I don't know what the implications of doing that are.

Finally, you can format code in GitHub Issues using the syntax shown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

**Comment by gitname** [comment]
>Finally, you can format code in GitHub Issues using the syntax shown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

@Motion4Life, I was able to edit your post (I didn't know I could do that!) and add the backticks to format the code snippets.
