### ISSUE TITLE
npm run deploy not actually committing anything to gh-pages branch

### ISSUE THREAD

**Issue by srosebattles** [gitname/react-gh-pages#112]
I have an app where gh-pages is installed and the scripts are defined in package.json, and npm run deploy seems to run just fine, but nothing is actually committed or deployed to the gh-pages branch. I am trying to attach screenshots of my console output but no dice so far.

**Comment by srosebattles** [comment]
https://github.com/srosebattles/quoting_clock

This is the repo by the way. ^

I'm using git version 2.10.1, npm: 8.19.2, node: 18.10.0,

**Comment by gitname** [comment]
Hi @srosebattles, thanks for including a link to the repository.

> nothing is actually committed or deployed to the gh-pages branch

I looked at the `gh-pages` branch (here: https://github.com/srosebattles/quoting_clock/tree/gh-pages) and saw that it contains the same commits as the `master` branch (except for one). In other words, it contains the app's "source" code, as opposed to just containing a "built" version of the app (the latter is what I expect to happen after someone follows the tutorial). Note: This is not to mention the `docs/build` folder that is there, which I assume was added manually while debugging.

I recommend creating a new repository, then going through the tutorial verbatim--without a custom domain name--and make sure that works (please report back if it doesn't work as I would want to reproduce that issue on my end!); and then, once that "base case" works on your machine, customize the domain name. Some people have found the following Issue helpful when using a custom domain: https://github.com/gitname/react-gh-pages/issues/89#issuecomment-1207271670

**Comment by gitname** [comment]
I confirmed the instructions in the tutorial still work for me, both with Node v16 and Node v18.

The `master` branch contains the app's "source" code and the `gh-pages` branch contains the app's "built" code.

![image](https://user-images.githubusercontent.com/7143133/194611947-cf042b26-5529-43b8-8f5f-08698ce08d40.png)

![image](https://user-images.githubusercontent.com/7143133/194612074-90e166fb-6e5d-4cb4-9012-cf703c710254.png)

#### Node 16 + TypeScript

```shell
$ node --version & npm --version & git --version & npm view gh-pages version & npm view react-scripts version
v16.17.0
8.15.0
git version 2.34.0.windows.1
4.0.0
5.0.1
```

- Repository: https://github.com/gitname/temp-react-gh-pages-issue112-node16
- Web page: https://gitname.github.io/temp-react-gh-pages-issue112-node16/

#### Node 18 + TypeScript

```shell
node --version & npm --version & git --version & npm view gh-pages version & npm view react-scripts version
v18.10.0
8.19.2
git version 2.34.0.windows.1
4.0.0
5.0.1
```

- Repository: https://github.com/gitname/temp-react-gh-pages-issue112-node18
- Web page: https://gitname.github.io/temp-react-gh-pages-issue112-node18/

**Comment by gitname** [comment]
> I am trying to attach screenshots of my console output but no dice so far.

@srosebattles, assuming you're still facing this issue, I do think screenshots would be helpful to me.

**Comment by gitname** [comment]
Closing because I failed to reproduce the issue and due to lack of response.
