### ISSUE TITLE
https://github.com/srosebattles/quoting_clock

### ISSUE THREAD

**Issue by Ooverapp77** [gitname/react-gh-pages#113]
https://github.com/srosebattles/quoting_clock

This is the repo by the way. ^

I'm using git version 2.10.1, npm: 8.19.2, node: 18.10.0,

_Originally posted by @srosebattles in https://github.com/gitname/react-gh-pages/issues/112#issuecomment-1270757528_

**Comment by gitname** [comment]
Hi @Ooverapp77, I don't understand the original post or why your account closed and then reopened this issue. It looks to me like bot/script behavior gone awry. Will you explain (or close this issue permanently)?

**Comment by gitname** [comment]
Closing due to lack of response.
