### ISSUE TITLE
step 6 - possibly missing 'git init' before 'git remote add origin...'

### ISSUE THREAD

**Issue by radubartan** [gitname/react-gh-pages#115]
In [step 6](https://github.com/gitname/react-gh-pages#6-add-a-remote-that-points-to-the-github-repository) - when trying to run `git remote add origin https://github.com/{username}/{repo-name}.git` 
I got this error: `fatal: Not a git repository`.

Following [this advice](https://stackoverflow.com/a/4630763/7191056) I ran `git init` before `git remote add origin https://github.com/{username}/{repo-name}.git`. 
That worked for me.

Just thought I would let someone know...

**Comment by gitname** [comment]
Hi @radubartan, thanks for expressing this feedback.

I don't expect people to have to run `$ git init` in Step 6, provided they followed the previous steps verbatim. Step 2 (i.e. "Create a React App") will run `create-react-app`, which automatically creates a Git repository. 

When you ran the `$ git remote ...` command the first time (when you got that error), were you in the root folder of the repository (i.e. the folder where the `package.json` file resides)?

**Comment by radubartan** [comment]
@gitname - I may have been in the root folder - can't quite remember. Thanks for responding to this issue. I appreciate it.

**Comment by achilleasmitos** [comment]
Perhaps I can shed some light into this matter. It's as simple as: did you use yarn or npm to create the react app? In the case of npm/npx a git repository is indeed initialized together with the rest of the code. In the case of yarn, it is not :)

**Comment by radubartan** [comment]
@achilleasmitos - Thank you good sir.

**Comment by gitname** [comment]
Thanks, @achilleasmitos, for clarifying that. Closing issue as the instructions refer only to npm and not to yarn.
