### ISSUE TITLE
React App page is not opening to home.js

### ISSUE THREAD

**Issue by 4-Leafs-Code** [gitname/react-gh-pages#122]
When I click on my site link, https://4-leafs-code.github.io/CloverBaxter/  my  app is loading but it is not starting on the homepage.   
   
![image](https://user-images.githubusercontent.com/105990331/205529713-27f2dc1f-c3f0-415e-ae3b-8dc4fbc148fa.png)      
    
If I click home, my page redirects to the right page but the url changes to: https://4-leafs-code.github.io/  but if I type that into a new page It returns a 404 message.    
![image](https://user-images.githubusercontent.com/105990331/205529746-f9014bee-0107-44c9-a37d-0daaba3608e2.png)    
   
 This is my set up:
![image](https://user-images.githubusercontent.com/105990331/205530481-da3d716c-219a-4b9e-88b4-b4bc751cb944.png)     
![image](https://user-images.githubusercontent.com/105990331/205530694-3f342503-7727-4dfb-b634-f9654f5f6bc8.png)   
![image](https://user-images.githubusercontent.com/105990331/205530725-074229c9-c965-4e89-a824-141f66d65d55.png)   
![image](https://user-images.githubusercontent.com/105990331/205530776-bbe8f8b9-348b-42c5-9885-82dd5035dd99.png)   
![image](https://user-images.githubusercontent.com/105990331/205530835-396c77a7-8ed1-473f-833e-a4729e9a3795.png)   
![image](https://user-images.githubusercontent.com/105990331/205530875-28011822-f79e-47a7-8825-7574d0b1035e.png)   
   
I'm not sure where I am going wrong here or how to fix it. When I research, all of the results are about a compleatly blank page but that is not what is happening here. Any advice would be great. Thank you.

**Comment by 4-Leafs-Code** [comment]
I fixed it, you can close this issue. I changed my repo name 4-leafs-code.github.io . My site url is: https://4-leafs-code.github.io/
I kept thinking about what you said and saw some other profiles with the  the short url I needed.  So, yeah, it fixed the problem. Thank you so much!!!

**Comment by gitname** [comment]
Thanks for following up here. I'll close the issue.
