### ISSUE TITLE
while depolying its shows black screen

### ISSUE THREAD

**Issue by ARUNREACT** [gitname/react-gh-pages#140]
Hi, I have the same issue with my webpage https://arunreact.github.io/arun/ , I think I did everything right but it is blank  Can someone help me out? :D

**Comment by gitname** [comment]
Hi @ARUNREACT, I visited that link (about 1 minute ago, which is about 2 hours after you posted the comment above) and saw a non-blank page.

![image](https://user-images.githubusercontent.com/7143133/226433866-4e69fcf6-ba3a-4744-91a0-2267498031a4.png)

I assume you got things sorted out. For that reason, I will close this issue.
