### ISSUE TITLE
React docs no longer recommend `create-react-app`

### ISSUE THREAD

**Issue by esau-morais** [gitname/react-gh-pages#143]
I think it's time to stop recommending `create-react-app` and maybe update the docs

**Comment by gitname** [comment]
Hi @esau-morais, I am confused about this Issue. Will you elaborate? Is there something about `create-react-app` that you consider counterproductive?

**Comment by gitname** [comment]
Thanks for clarifying and thanks for bringing it to my attention. 

Here are some related references I found:
- https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741
- https://twitter.com/dan_abramov/status/1636827365677383700

I'll be away on vacation until April 20 and will look into this once I'm back.
