### ISSUE TITLE
code is deployed but not showing content 

### ISSUE THREAD

**Issue by vivekkapoor240** [gitname/react-gh-pages#147]
This is my deployed site url : https://vivekkapoor240.github.io/keeper/
I have uploaded the code in master branch  of repo name: vivekkapoor240/keeper
I have deployed the code but after deployment the content inside it is not rendering .

**Comment by gitname** [comment]
For future reference, here's a link to the associated GitHub repository:
- https://github.com/vivekkapoor240/keeper

Hi @vivekkapoor240 , I looked at the code in the above GitHub repository and it did not look like the code generated by `create-react-app`. I recommend creating a new GitHub repository and going through the steps in the tutorial (in `README.md` of this repository) verbatim; then applying that experience to your current project.

**Comment by gitname** [comment]
Closing because the project is not CRA-based. I made some recommendations in my previous comment.
