### ISSUE TITLE
Blank website after deploying with gitpages

### ISSUE THREAD

**Issue by Catherine-Ge** [gitname/react-gh-pages#156]
Hi everyone, this is my first time trying to deploy something. I'm trying to deploy using the build branch because my main branch has some files which I created before writing this website with React so I guess that maybe a bit messy.
Here is the website: https://catherine-ge.github.io/Fun-Facts/
Here is my repo: https://github.com/Catherine-Ge/Fun-Facts/tree/build

**Comment by gitname** [comment]
Hi @Catherine-Ge, the first thing that jumps out at me is that the `package.json` file in the current repository does not have a `homepage` property. I didn't look at any other files. I recommend going through the tutorial in this repo as-written (you can create a **new** repository for that, and then delete it afterward) and then apply that experience to the current `Fun-Facts` repository.

**Comment by gitname** [comment]
Also, the website is non-blank when I visit it.

![image](https://github.com/gitname/react-gh-pages/assets/7143133/c4073513-b328-4642-936d-1e2125cc86e3)

I like the color scheme!
