### ISSUE TITLE
Translate instructions into traditional Chinese (offer)

### ISSUE THREAD

**Issue by creaper9487** [gitname/react-gh-pages#167]
Hi. I really appreciate this tutorial and wants to share with my classmates. However, language might be a barrier for them when following steps. Though this might not be a problem for me, people like my classmates that are not familiar with English might need some helps. If you are interested, I would love to provide a accurate, native speaker toned translation of traditional Chinese to make this first tutorial result on Google even better. I'm looking forward to your opinion about this.

**Comment by gitname** [comment]
Hi @creaper9487, thanks for offering. I like the idea of having the tutorial exist in other languages besides English. 

I have a concern about ongoing maintenance of the translation; specifically, I don't know how the Chinese version would be kept in sync with the English version as the English version changes over time.

If you provide an accurate, native speaker-toned translation of the current version of the tutorial into traditional Chinese, you could post a link to it here in this issue. If you do that, I would update the English version with the link. That way, people that are more comfortable with traditional Chinese can find the Chinese version.

```mermaid
flowchart LR
  engtut["English tutorial<br>(react-gh-pages)"] -- Link --> chitut["Chinese tutorial<br>(e.g. react-gh-pages-chinese)"]
  subgraph "gitname"
    engtut
  end
  subgraph "creaper9487"
    chitut
  end
```

I think, if you were to create a [fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo) of this repository (and then, in the fork, replace the English instructions with a Chinese version), there will be some GitHub features available that facilitate keeping the two repositories "in sync."

**Comment by creaper9487** [comment]
I've finished all the translation work!
Here's the [link](https://github.com/creaper9487/react-gh-pages-zh) , additionally, I assume the function that can keep the tutorials in sync is the "Sync fork" function on GitHub, I will utilize it in my best effort to keep things on date! Thank you for giving me the chance to contribute. If there were any error about the translated README.md, please feel free to correct me.

**Comment by gitname** [comment]
Thanks, @creaper9487! I'll revisit this this weekend (I'm pretty busy with my day job during the week).

**Comment by gitname** [comment]
Hi @creaper9487, I added a link to your comment above, to the `README.md` file; in a new section entitled, "Translations." You can adjust your comment above to say whatever you want (including writing it in Traditional Chinese).
