### ISSUE TITLE
Blank Page Load

### ISSUE THREAD

**Issue by ryanmchenry2** [gitname/react-gh-pages#17]
Hi gitname -

Troubleshooted my way through your tutorial, thanks in advance for the help. Ran into an issue in that the page that loads is simply blank and white, although it does load the <title> correctly from my index.html. any ideas?

**Comment by AlanPedro** [comment]
Similar issue, did you manage to solve this?

**Comment by jonathonwpowell** [comment]
I had a similar issue and managed to solve it.  Make sure that the homepage defined in the package.json file is in the correct format  `http://{username}.github.io/{repo-name}` otherwise the resources will fail to load as it will look in the wrong place.

**Comment by danceyoung** [comment]
I had a similar issue, but not solve it. The property homepage is also correct. @jonathonwpowell

**Comment by jonathonwpowell** [comment]
@danceyoung Have you checked the network tab on the browser Dev tools to see exactly where the requests are going? That is what tipped me off to what was happening

**Comment by danceyoung** [comment]
<img width="1022" alt="wx20181128-094245 2x" src="https://user-images.githubusercontent.com/1777025/49123037-0b46d900-f2f2-11e8-9a79-3317b16c89fe.png">
repository :https://github.com/danceyoung/trycatch-intereactiveUIs @jonathonwpowell 
thanks

**Comment by danceyoung** [comment]
@jonathonwpowell 
Hi, i have fixed through  the issue https://github.com/gitname/react-gh-pages/issues/3
setting react router's basename prop to repository name
thanks

**Comment by Ronnehag** [comment]
> @jonathonwpowell
> Hi, i have fixed through the issue #3
> setting react router's basename prop to repository name
> thanks

Awesome! I had my first router path set to '/' so it loaded the page without main content, but when I clicked the home link it all rendered. Changed it to my repo-name worked.

**Comment by LOGANLEEE** [comment]
Thank you i solved URL and router issue 👍

**Comment by Qubaish** [comment]
Hi Guys, 

I am also facing the same issue but in my case the resource are getting from root directory instead of repo-name.
e.g
https://qubaish/github.io/vendor.js /// not found

but ideally it should pick from this path
https://qubaish/github.io/repo-name/vendor.js // found

any suggestion what i am doing wrong ? 

Thanks

**Comment by jonathonwpowell** [comment]
@Qubaish What is the value for "homepage" in your package.json file?  Make sure it follows this format: https://{username}.github.io/{repo-name}

**Comment by Qubaish** [comment]
@jonathonwpowell , I am using exactly same format: https://qubaish.github.io/news-feed/

**Comment by Abbaskt** [comment]
> @jonathonwpowell
> Hi, i have fixed through the issue #3
> setting react router's basename prop to repository name
> thanks

Can you explain it more briefly

**Comment by rahulseetharaman** [comment]
I have a similar issue and I don't use react router at all
