### ISSUE TITLE
App deploys successfully but rendering empty page (Unexpected Token)

### ISSUE THREAD

**Issue by YasirAlibrahem** [gitname/react-gh-pages#172]
# Category

Which of these applies to you? _(Select all that apply)_

- [x] I'm following the tutorial as-written from start to finish
- [ ] I'm using a custom domain (note: not covered in tutorial)
- [x] I'm using React Router (note: not covered in tutorial)

# Step

Which step of the tutorial do you want someone to help you with? _(Select one)_

- [ ] Step number: _(put the number here)_
- [x] Something else

# Links

Tell us where we can find your code and your GitHub Pages site:

- GitHub repository (source code): https://github.com/YasirAlibrahem/yasiralibrahem.github.io/tree/gh-pages
- GitHub Pages site (deployed app): https://yasiralibrahem.github.io/

# Everything else

_You can put whatever you want into this section._
After deployment, I'm getting a blank page. This [issue](https://github.com/gitname/react-gh-pages/issues/159) points to a similar problem though different console error. It was resolved by implementing HashRouter, which I tried, but still facing the same problem. I'm getting an _[Unexpected Token](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_token?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)_

![Image](https://github.com/gitname/react-gh-pages/assets/20503458/9c526359-eca2-4f46-b2e3-d3fab69c7607)

**Comment by YasirAlibrahem** [comment]
Fixed it. I'm running this as a user site, and I didn't need the _"homepage"_ variable in the `package.json` file.

**Comment by gitname** [comment]
Thanks for following up!
