### ISSUE TITLE
Blank Page. Using React Router

### ISSUE THREAD

**Issue by JoaoGuimaraes22** [gitname/react-gh-pages#176]
# Category

Which of these applies to you? _(Select all that apply)_

- [x] I'm following the tutorial as-written from start to finish
- [ ] I'm using a custom domain (note: not covered in tutorial)
- [x] I'm using React Router (note: not covered in tutorial)

# Step

Which step of the tutorial do you want someone to help you with? _(Select one)_

- [ ] Step number: _(put the number here)_
- [x] Something else

# Links

Tell us where we can find your code and your GitHub Pages site:

- GitHub repository (source code):  https://github.com/JoaoGuimaraes22/danielacaturra
- GitHub Pages site (deployed app):  https://joaoguimaraes22.github.io/danielacaturra/

# Everything else

Blank Page. Works perfect locally. Using React Router. Tried using HashRouter, still blank. Open to anything.

...

**Comment by gitname** [comment]
Hi @JoaoGuimaraes22, here are some options: https://github.com/gitname/react-gh-pages/issues/104#issuecomment-1203373499

**Comment by gitname** [comment]
Thanks for including the links in the issue description. I visited the deployed site and was able to navigate to different routes (looks like you are using hash-based routes). Since it looks to me like you got routing working and since routing is not part of the tutorial, I will close this issue.
