### ISSUE TITLE
Deployment resets custom domain when build folder lacks CNAME file

### ISSUE THREAD

**Issue by emilkarl** [gitname/react-gh-pages#19]
Every time I deploy my custom domain on Github for the page is reset to `blank`? Does anyone have a solution for that?

**Comment by ottobonn** [comment]
Github reads a file called `CNAME` in the root directory of the `gh-pages` branch to set the custom domain. To make the build keep your custom domain, you just need to copy the `CNAME` file into the build directory. 

First, create a file called `CNAME` in your source code. I put mine in the root directory of my app repository. The contents of the file are your domain:

```
www.example.com
```

Now, edit the `package.json` file, to add one step to the `predeploy` script:

```
  "scripts": {
    "predeploy": "npm run build && cp CNAME build/CNAME",
    "deploy": "gh-pages -d build"
  },
```

Note the addition of the extra step, `cp CNAME build/CNAME`. This step simply copies your `CNAME` file into the build directory. When you deploy, your build directory will be the contents of the `gh-pages` branch, and Github will read the `CNAME` file to get your custom domain.

**Comment by ne-v0y** [comment]
OMG I just got mine fixed and it took me almost a day... for those who have the same issue, in addition to @ottobonn 's solution, don't forget to change your homepage setting to `homepage: "YOUR.CUSTOM.DOMAIN"`

**Comment by lpshanley** [comment]
On a windows machine you may need to use: 
`
"predeploy": "npm run build && COPY \"CNAME\" \"./build/CNAME\"",
`

**Comment by explooosion** [comment]
You can move `CNAME` into `public/`.

![image](https://user-images.githubusercontent.com/13682994/64585400-39059600-d3cb-11e9-8cc9-bb86a1866fbf.png)
