### ISSUE TITLE
Blank page on deployment

### ISSUE THREAD

**Issue by aarushi-shanker** [gitname/react-gh-pages#194]
# Category

I am trying to deploy my app but all it shows is a blank page. Please help me out.
It is vite+react app and uses react router

You can find my code and your GitHub Pages site:

![Screenshot 2024-05-23 163239](https://github.com/gitname/react-gh-pages/assets/156585940/03344667-fb9f-446c-b508-5e8b85552484)

**Comment by OvaisKhanday** [comment]
![image](https://github.com/gitname/react-gh-pages/assets/29146341/befa13f5-d6b3-4634-920d-57f437fe069f)
Put . before the src and href
