### ISSUE TITLE
Can not update Github Page after deploy

### ISSUE THREAD

**Issue by khuong291** [gitname/react-gh-pages#2]
Hi gitname, I follow your tutorial to final step, it works:

https://github.com/khuong291/home
https://khuong291.github.io/home/

But when I change the title: "To get started, edit src/App.js and save to reload." to "This is Khuong's website" and push to master branch, it does not change. So I need to delete repo and deploy again?

**Comment by khuong291** [comment]
I realize that it need times to update content to host. Now it shows the content I updated.

**Comment by StrawHatAaron** [comment]
how much time did it need @khuong291? My deployment went great, but I am not seeing any new content I made after 12 hours so I am thinking I might have an issue :/

**Comment by gitname** [comment]
@StrawHatAaron, thanks for closing the loop here and thanks for searching through existing Issues prior to posting (or not posting) one.

Glad you found the tutorial helpful and that you got this particular issue sorted out!

For future reference (for future readers), the wait time has typically been about 30-60 seconds, in my experience.

**Comment by iamtheasad** [comment]
In my case `npm run deploy` works thanks @StrawHatAaron

**Comment by jasonma1127** [comment]
That's weird, because I can't see the complete update that I made, there is always somthing missing on my website

**Comment by jasonma1127** [comment]
> That's weird, because I can't see the complete update that I made, there is always somthing missing on my website

![image](https://user-images.githubusercontent.com/33441316/126167350-ceed7bbe-9440-402e-80e5-d5cc28e4695b.png)

In this case, I couldn't see the <div class="home-title move"> on my website

**Comment by michaelfan0310** [comment]
> how much time did it need @khuong291? My deployment went great, but I am not seeing any new content I made after 12 hours so I am thinking I might have an issue :/
> 
> EDIT: Wait I did not run `npm run deploy`. After I ran that and pushed it again it works! thank you for all the work in this tutorial! I found it very helpful.
> 
> Sorry for the false alarm

Thanks for your false alarm, me either. @🙃
