### ISSUE TITLE
Tried publishing build but instead published README.md

### ISSUE THREAD

**Issue by simonhoyos** [gitname/react-gh-pages#23]
Followed the instructions and got README.md published

I'm using:
npm: 6.4.1
node: 10.15.1
CRA: 2.0.4
React: 16.8.3

My `package.json`:

```
"homepage": "https://simonhoyos.github.io"
"scripts": {
    ...
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build"
  }
```

this is the result:
https://simonhoyos.github.io/

**Comment by viery365** [comment]
@simonhoyos I tried the same and got a README.md file as well. But now I see your result is working. Please, what did you do to make it work?

**Comment by simonhoyos** [comment]
@viery365 I found a solution yesterday. Apparently, this "issue" is related to how GitHub pages work.
A normal repository will be published from gh-pages branch (or whatever you've set as source branch). But, for personal websites [username].github.io the source branch is always set to master.

To make this work do this:
1. create a new branch `git checkout -b dev`.
2. push it to your repository `git push -u origin dev`.
3. go to your repository > settings > branches.
4. update your default branch to your newly created branch.
5. change deploy script for `"deploy": "gh-pages -b master -d build"`.
6. run `yarn deploy`.

This will build your app to master, so you will have to develop on your new branch.

Hope this helps.

Maybe this can be added to the documentation.

**Comment by viery365** [comment]
@simonhoyos Thank you so much! This is precious!

**Comment by DamianoSilverhand** [comment]
@simonhoyos  After having followed your instructions, the ReadMe is gone from the view but it's now giving a 404 page not found error. Is there any other way to get it to work?

**Comment by ChrisWU012** [comment]
> 

I got the same problem: ```Unexpected Application Error!
404 Not Found```

What to do next?

**Comment by gitname** [comment]
>I got the same problem: Unexpected Application Error! 404 Not Found

Hi @ChrisWU012, since this issue is about the README.md file being published, will you (a) create a new Issue and (b), in that new Issue, include a link to your GitHub repository and a link to the deployed app?

**Comment by ChrisWU012** [comment]
> > I got the same problem: Unexpected Application Error! 404 Not Found
> 
> Hi @ChrisWU012, since this issue is about the README.md file being published, will you (a) create a new Issue and (b), in that new Issue, include a link to your GitHub repository and a link to the deployed app?

I found the problem. In my react project, I used `react-router-dom` for routing, and redirect the undefined endpoints (`*`) to the error page. 
As the github Pages change the endpoint to the repo name, my react project didn't recognise that and redirected me to the error page.

To solve this problem, I made a change: `<Route exact path="*" component={HomePage} />`
