### ISSUE TITLE
Failed to deploy after failed authentication

### ISSUE THREAD

**Issue by Nugasnakarmi** [gitname/react-gh-pages#24]
gh-pages -d build shows failed authentication due to invalid username or password

` gh-pages -d build

fatal: TypeInitializationException encountered.
   The type initializer for 'Microsoft.Alm.Cli.Program' threw an exception.
fatal: TypeInitializationException encountered.
   The type initializer for 'Microsoft.Alm.Cli.Program' threw an exception.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Nugasnakarmi/OfficeRec.git/'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office@0.1.0 deploy: `gh-pages -d build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office@0.1.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by buzzdeeDE** [comment]
Hi! i do have the same issue... any solution here?
Maybe because of the 2-Factor Auth?

**Comment by Nugasnakarmi** [comment]
I solved it by changing the credential helper to win cred ( previously credential manager)

**Comment by buzzdeeDE** [comment]
After using a ssh key and switching from https to ssh it worked for me to. thx
