### ISSUE TITLE
Can I change the GitHub 'default' branch without affecting `npm run deploy`?

### ISSUE THREAD

**Issue by cagross** [gitname/react-gh-pages#32]
Hello.  I should first say that for a side project, I used create-react-app to build a simple React app locally.  I then used the instructions in this repo to push my app to GitHub pages.  The instructions were very clear, and worked perfectly on the first try--no hassle at all--amazing.  So thanks very much for that.  

I have a question though.  Can I safely change the 'default' branch in my GitHub settings ([screenshot](https://imgur.com/a/MoV1v5l)) without it affecting `npm run deploy`?  Here is more info on that.

I did indeed carry out all your instructions, including step 8.  The GitHub repo for my app can be seen here:  https://github.com/cagross/react-specials  As you described, the GitHub repo has is both a `master` branch and a `gh-pages` branch.  Separately, I continue to develop my app locally, and periodically push my edits to GitHub pages, using `npm run deploy`.  

In the GitHub repo, the 'default' branch seems to have been automatically set to `gh-pages`.  I would like to change it to `master` ([screenshot](https://imgur.com/a/MoV1v5l)).  Does `npm run deploy` require that the GitHub 'default' branch be set to `gh-pages`?  Or can I safely change the GitHub 'default' branch to `master` without it affecting `npm run deploy`?

Maybe a more precise question is:  to what GitHub branch does `npm run deploy` push edits? Does it push edits to the gh-pages branch, regardless of what I have set for the 'default' branch in my [GitHub settings](https://imgur.com/a/MoV1v5l)? Or does `npm run deploy` push edits to whatever branch I have set as 'default' in my GitHub settings? 

I *think* I can change the GitHub 'default' branch without affecting `npm run deploy`.  `npm run deploy` will push to whatever remote branch I have configured in my local Git repo--correct?  If so, whatever I have set as 'default' branch in my GitHub settings doesn't matter.  Am I on the right track there?

The reason I’d like to change the GitHub 'default' branch to `master` is because the `master` branch is the branch that actually displays the code I wrote, as well as the README file for the GitHub repo.  So I'd like to share a link to this repo with collaborators/potential employers, and have my code/README file displayed by default (rather than forcing them to change the branch to master).  I realize I can share a direct link to the master branch, and I'll do that as a fall back.

Thanks.

**Comment by Trifex** [comment]
Having experimented with this, yes. You should be able to set your master branch to the default branch, **as long as you make sure to that the github pages source in the settings is still the `gh-pages` branch**.

To answer your other question, `npm run deploy` will always push to the `gh-pages` branch, regardless of what your default is.

Here's [my repository](https://github.com/Trifex/react-todo-list), and you can see that the master branch is still set to default. I actually created my repository with the master branch as default and installed and used `gh-pages` later and it still worked like a charm.

**Comment by cagross** [comment]
Hey thanks for the reply--I appreciate it.  I actually decided for several reasons to move my app away from GitHub pages, and to Heroku.  So I'm not able to test out your suggestions.  But they are good to know for the future, in case I need to add something else to GitHub pages.  I think we can call this issue closed then.

**Comment by alikhutaba** [comment]
hi Trifex

can you explain how you did it??? the master branch is still set to default? how!
