### ISSUE TITLE
How to add a license file to the `gh-pages` branch?

### ISSUE THREAD

**Issue by cagross** [gitname/react-gh-pages#33]
Hello.  I've carried out the instructions in your README and was able to deploy my local app to GH pages without issue.  I can also edit my app locally, and continue to push those edits to GH pages using `npm run deploy`, which has worked great so far--thanks for that.  But how can I properly add a license file to the `gh-pages` in GitHub?  As a test, I just added one manually, via a commit done within GitHub.  After, as a test, I tried to deploy again with `npm run deploy`.  It then displayed this in its output:

```
error: unable to stat just-written file LICENSE: No such file or directory
fatal: Could not reset index file to revision 'origin/gh-pages'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactinterface@0.1.0 deploy: `gh-pages -d build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactinterface@0.1.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\snarl\AppData\Roaming\npm-cache\_logs\2020-02-29T14_15_14_746Z-debug.log
```

Any ideas on how to troubleshoot/resolve?

**Comment by gitname** [comment]
Hi @cagross, sorry I'm replying only now (almost 3 years after you reported this). 

You can put the `LICENSE` file in the `public` folder to achieve what you want.

Details: On your `master` branch (a.k.a. `main` branch), anything you put in the `public` folder will be copied to the root folder of the distributable app's file tree during the build process. Everything in the distributable app's file tree will end up on the `gh-pages` branch by the end of the deployment process.

Reference: https://create-react-app.dev/docs/using-the-public-folder/
