### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by ilyamordasov** [gitname/react-gh-pages#38]
I've done according your instruction, but everything is pushed to github repo but nothing to github pages. I added "homepage":"..." to package.json, and got nothing. But my terminal said
```
im@im:~/Desktop/figma-app$ npm run deploy

> figma-app@0.1.0 predeploy /home/im/Desktop/figma-app
> npm run build


> figma-app@0.1.0 build /home/im/Desktop/figma-app
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  39.39 KB  build/static/js/2.a88a2725.chunk.js
  777 B     build/static/js/runtime-main.a0ad3164.js
  648 B     build/static/js/main.e84e2243.chunk.js
  556 B     build/static/css/main.d1b05096.chunk.css

The project was built assuming it is hosted at /figma/.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  bit.ly/CRA-deploy


> figma-app@0.1.0 deploy /home/im/Desktop/figma-app
> gh-pages -d build

Username for ...
Password for ... 
Published

```

**Comment by lokesh-kurre** [comment]
[check this link](https://github.com/gitname/react-gh-pages/issues/60#issuecomment-852007772)
Check the GitHub Page sources, and update according to above link.
Branch -> gh-pages
folder -> root

It may possibly be help you out!! 🙃🙃

**Comment by catherineisonline** [comment]
Did you find the solution to this issue?

**Comment by SethCram** [comment]
@lokesh-kurre the previous issue you linked solved my problem, but why isn't this mentioned in the README?

**Comment by gitname** [comment]
Thanks @lokesh-kurre for providing that potential solution to people.

I added it to the README a few minutes ago after reading from several people that that step made the difference between a working deployment and a non-working deployment for them.

Here's the newly-added section:
https://github.com/gitname/react-gh-pages#8-configure-github-pages

**Comment by gitname** [comment]
For those of you still running into a "Page not found" issue, please include a link to your repo.
