### ISSUE TITLE
Code is deployed, but my page is showing blank

### ISSUE THREAD

**Issue by palak-porwal** [gitname/react-gh-pages#41]
https://github.com/palak-porwal/monster

My git hub repository

https://palak-porwal.github.io/monster/

My link!

Please help

**Comment by JNotelddim** [comment]
I'm having the same issue at
https://jnotelddim.github.io/jaredm.me/
(url might change over the next couple days as I try and correct it to https://www.jaredm.me )

**Comment by kanarian** [comment]
I had the same problem:
Changing  `<link rel="manifest" href="/github.io/monster/manifest.json"/>` to `<link rel="manifest" href="/manifest.json"/>` fixed it for me.

**Comment by gitname** [comment]
Hi @palak-porwal, I visited https://palak-porwal.github.io/monster/ and checked the web browser's JavaScript console. The console contained several errors, showing that the page failed to load some chunks of your app (i.e. some JavaScript files).

![image](https://user-images.githubusercontent.com/7143133/213773290-39e42633-fa32-479d-a955-fafa06edc29d.png)

The URLs in the error message seem to have an extra `"/github.io"` in them. I suspect there is an issue with the `homepage` URL in your repo. 

Thanks for including a link to your repo. I checked the `package.json` file and saw [the `homepage` URL](https://github.com/palak-porwal/monster/blob/master/package.json#L5) has a typo:

```diff
-  "homepage":"https://palak-porwal/github.io/monster",
+  "homepage":"https://palak-porwal.github.io/monster",
                                   ↑
```

I recommend fixing that typo and redeploying.
