### ISSUE TITLE
fatal: A branch named 'gh-pages' already exists.

### ISSUE THREAD

**Issue by adamalston** [gitname/react-gh-pages#44]
I am trying to deploy my app and am getting this error. I have tried running `rm -rf node_modules/gh-pages/.cache` to no avail. I also tried manually deleting `node_modules/gh-pages/.cache` and that did not work either.

For troubleshooting, I am on a Mac.

**Comment by adamalston** [comment]
Update and possible solution:

I was able to get `gh-pages` to work correctly:

1. Traverse the file structure of the project to `node_modules/gh-pages/bin/gh-pages-clean.js`
2. Run `gh-pages-clean.js`
3. Create a new build of the project via npm `npm run build`
4. Lastly, deploy again to GitHub pages via `npm run deploy`

It seemed that a few people were running into issues with `gh-pages` and React in particular. In the long run, I didn't know if the solution outlined above was sustainable so I instead chose to remove `gh-pages` from my project entirely and host it on Netlify.

**Comment by ARANY** [comment]
@AbhishekCode I am currently facing the same issue. How can I traverse according to your first step

**Comment by codewithnitesh** [comment]
@ARANY -  Run the below command in the project root folder.
`node node_modules/gh-pages/bin/gh-pages-clean.js`

@adamalston - Thanks for sharing the steps. Worked fine for me.

**Comment by witcherhunter** [comment]
how can run gh-pages-clean.js?

**Comment by VardaPanchal005** [comment]
it didnt work for me.Any other solution?

**Comment by miracle5284** [comment]
Try [this](https://www.npmjs.com/package/gh-pages?activeTab=readme#:~:text=Tips,gh%2Dpages.)
