### ISSUE TITLE
react app hosted using github pages showing blank white screen

### ISSUE THREAD

**Issue by rohan8660** [gitname/react-gh-pages#45]

**Comment by rohan8660** [comment]
![image](https://user-images.githubusercontent.com/40888098/88453514-3eee5380-ce85-11ea-83a6-e2c80e757123.png)

**Comment by rohan8660** [comment]
![image](https://user-images.githubusercontent.com/40888098/88453525-5299ba00-ce85-11ea-8afe-ca9b360144af.png)

**Comment by rohan8660** [comment]
site link : https://rohan8660.github.io/IEEE_GIT-Website-Contest-Let-s_React/

**Comment by DarkMG73** [comment]
Did you ever figure this out? I am experiencing the same issue.
