### ISSUE TITLE
Create-react-app automatically puts index.html in public

### ISSUE THREAD

**Issue by brookebachman** [gitname/react-gh-pages#46]
I had an issue where the read me was the only thing on Github pages. Add to the documentation that they have to have their index.html outside of all folders.

**Comment by gitname** [comment]
Hi @brookebachman, thanks for sharing your experience here and suggesting an edit to the tutorial. Sorry I waited so long to respond, which has been the case with respect to many of the Issues here. I'm starting to catch up with them.

I'll respond here as though this is a fresh Issue, but I understand it is 17 months old and may no longer be affecting you. As far as I'm concerned, you can close this Issue without responding to the questions I post below.

---

>Add to the documentation that they have to have their index.html outside of all folders.

I don't understand what you meant by "outside of all folders." 

`create-react-app` (e.g. via `$ npx create-react-app my-app`) creates the `index.html` file in the root of the `public/` folder by default. I have always left it there in my projects and, with it there, have been able to successfully deploy React apps to GitHub Pages using the process described in the tutorial (as shown here).

![image](https://user-images.githubusercontent.com/7143133/154342341-4c02c212-540c-4786-b9e7-bb648c623da1.png)

![image](https://user-images.githubusercontent.com/7143133/154342772-a26c5ef0-5641-4487-86c3-62a615bf9381.png)

By "outside of all folders," do you mean the file has to be in the root of the _repository_, itself, as opposed to in the root of the `public/` folder?

**Comment by gitname** [comment]
Closing due to lack of response (10 months).
