### ISSUE TITLE
how to deploy second time i mean updated code 

### ISSUE THREAD

**Issue by rizwan92** [gitname/react-gh-pages#5]
how to deploy second time i mean updated code

**Comment by dangpro-1210** [comment]
Have you tried redeploy ?

**Comment by rizwan92** [comment]
Sorry man disturbed you it takes time to update latest changes in git hub pages

**Comment by rizwan92** [comment]
hey man i have another problem i changed my repository name form 
dashboard to nakul-dashboard then git page from 
```http://rizwan92.github.io/dashboard```` 
to 
```http://rizwan92.github.io/nakul-dashboard```
i changes git remote url form 
```  https://github.com/rizwan92/dashboard.git```
 to 
``` https://github.com/rizwan92/nakul-dashboard.git```
then homepage property in package.json 
```"homepage": "http://rizwan92.github.io/nakul-dashboard",```
then ran 
```npm run deploy 
```
nothing gets live

**Comment by dangpro-1210** [comment]
Can you show me the package.json ?

**Comment by dangpro-1210** [comment]
And also, open a new Issue.
This issue is old, so open a new one

**Comment by gitname** [comment]
Hi @rizwan92,

Regarding _deploying new code_: In my experience, after `$ npm run deploy` finishes running (whether for the first deployment or subsequent deployments), it typically takes approximately 1 minute for GitHub to serve the updated version of the app.

Regarding _changing your repository name_: Please open a new Issue with a title that reflects the new issue (thanks for recommending that, @dangpro-1210). In that issue, please include the output of the following commands:

```sh
$ git remote -v
$ cat ./package.json
```

The first command will display the URL to which Git is configured to push each branch of your repository. The second command will display the contents of your `package.json` file (thanks for recommend that as well, @dangpro-1210).

**Comment by gitname** [comment]
For future reference, the original behavior reported in this Issue is a duplicate of Issue #2.
