### ISSUE TITLE
'create-react-app' command doesn't exist...

### ISSUE THREAD

**Issue by codigoisaac** [gitname/react-gh-pages#57]
I have the app created with create-react-app but when I run this command it says 'command not found'.
Does this command really exists? My app is working, built and deployed and I don't have this command.

**Comment by adnjoo** [comment]
try npx create-react-app react-gh-pages

**Comment by gitname** [comment]
Thanks @adnjoo for stepping in an answering this question.

Hi @codigoisaac , preceding the command with `npx` will cause npm to download and install `create-react-app` if it's not already installed.

As for why you saw the `command not found` message, I don't think I'll be able to figure it out without knowing more about your environment. It may have been that `create-react-app` was installed globally at the time you created the app, and then was subsequently uninstalled.
