### ISSUE TITLE
Question: To which branch do you recommend I commit/push future changes?

### ISSUE THREAD

**Issue by TanyaGupta1901** [gitname/react-gh-pages#58]
For any new commits in local directory should they be pushed to master branch or gh-pages branch?

**Comment by lokesh-kurre** [comment]
Well, It's not necessary to commit in both the branches here.
In this case, actually deployment is done via the gh-pages branch,
which itself pushed (to gh-pages branch) when we run `npm run deploy`
according to the given procedure.

**Comment by gitname** [comment]
Thanks @lokesh-kurre for stepping in and answering this question.

Hi @TanyaGupta1901 , I recommend keeping source code on the `master` branch and the "distributable" version of the app on the `gh-pages` branch. 

To push source code changes (that you have committed to the `master` branch of your local repository) to the `master` branch of the repository on GitHub, you can run `$ git push origin master`. 

To generate a new distributable instance of the React app and push it to `gh-pages` branch of the repository on GitHub, you can run `$ npm run deploy`.

I posted some similar information a few minutes ago in a separate Issue, linked below: https://github.com/gitname/react-gh-pages/issues/69#issuecomment-1017110393
