### ISSUE TITLE
Getting Uncaught SyntaxError: Unexpected token '<' error in console.

### ISSUE THREAD

**Issue by anujrajak** [gitname/react-gh-pages#59]
Getting **Uncaught SyntaxError: Unexpected token '<'** error in console after I deployed the react app.

Url: https://anujrajak.github.io/

![image](https://user-images.githubusercontent.com/29977390/118235919-03278780-b4b3-11eb-8e50-e5e94f77d38d.png)

**Comment by laneschmidt** [comment]
hey @anujrajak seems to be working now! could you please share how you fixed it for me? i'm having a similar issue.

**Comment by gitname** [comment]
Hi @laneschmidt, if you create a GitHub Issue about the symptom(s) you observed while following this tutorial, I'll take a look.
