### ISSUE TITLE
my builds are getting cached in the browser...

### ISSUE THREAD

**Issue by fotoflo** [gitname/react-gh-pages#6]
Any way to reset the cache for each build?

**Comment by AbhishekCode** [comment]
i think you have to do that manually

**Comment by gitname** [comment]
Hi @fotoflo,

Do you mean that, when you visit your app's URL after you deploy a new version of your app, your web browser still shows you the previous version of your app?

I have thought of two reasons for which that might be happening:

1. The **Service Worker** (enabled by default in at least some versions of `create-react-app`) is serving the previous version of your app. I think you can work around this by reloading the page once. More information is available in [this GitHub Issue](https://github.com/facebook/create-react-app/issues/2398#issuecomment-304738903) in the `create-react-app` repo.
2. The web server (i.e. **GitHub Pages**) is still serving the previous version of the app. You can work around this by waiting for some time (e.g. 30 seconds) and then visiting the page.

**Comment by crisecheverria** [comment]
I follow your steps but, when the page load I think the webpack bundle process didn't run, the css is available but not my bundle.js components, here's my repo https://crisecheverria.github.io/peregrino/

**Comment by AbhishekCode** [comment]
@crisecheverria I think you are missing this https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#building-for-relative-paths

**Comment by crisecheverria** [comment]
Already have
`"homepage": "https://crisecheverria.github.io/peregrino",`
Still not working, also completely removed Links, Routes and more... just for test, and also didn't work

**Comment by gitname** [comment]
Hi @crisecheverria,

I visited the URL you provided and don't see anything indicative of an issue.

![image](https://user-images.githubusercontent.com/7143133/43818065-c01b47ee-9a91-11e8-9186-95e088824b79.png)

If you are still having an issue, I recommend you open a separate Issue on this repository (assuming you think the issue is related to this repository).

**Comment by gitname** [comment]
Closing because I have not heard back from @fotoflo in 3 weeks.
