### ISSUE TITLE
GitHub Pages shows 404 error when navigating to other routes

### ISSUE THREAD

**Issue by Sarika4497** [gitname/react-gh-pages#63]
![16267603562742806764158402205587](https://user-images.githubusercontent.com/82380307/126268752-33b3eb26-88e9-4f85-8e24-957d930d060a.jpg)
 I created my portfolio website but when I click on home or about me or skills or contact ...every time I found the error like 
![1626760492882636820505087115265](https://user-images.githubusercontent.com/82380307/126268934-f7c70f5c-683a-43a2-aed2-b8fee4d35380.jpg)
How I solve this problem

**Comment by T-Damer** [comment]
Looks like it's problem with `build` command, it creates `index.html` for main page only and javascript can not load new page. Problem is in `index.html` for every page, or in javascript files. I have the same issue, searched many time, nothing works. 

In your condition I can see, that route is `github.io/#home`, but it must be `github.io/myreactportfolio/#home`, check `<Router>` component, routes must be `<Route to='myreactportfolio/home component={Home} />` for example

**Comment by Teut2711** [comment]
It happened same for me. I just changed the homepage name to the github repo name and it worked.

**Comment by catherineisonline** [comment]
Having the same issue for a while, found any solution yet? :))

**Comment by DarkMG73** [comment]
Likewise, I have encountered the same issue.  I'll post back if I figure it out.

**Comment by DarkMG73** [comment]
Found the problem: capital letters in the repo name. I change the repo name to the same name, but with all lowercase letters (including the Homepage url in the package.json) and re-deployed. No 404 now. I get a white screen, which is a different problem, but the 404 is gone.

**Comment by catherineisonline** [comment]
> Found the problem: capital letters in the repo name. I change the repo name to the same name, but with all lowercase letters (including the Homepage url in the package.json) and re-deployed. No 404 now. I get a white screen, which is a different problem, but the 404 is gone.

I have everything in lowercase, however it doesn't help

**Comment by Teut2711** [comment]
Use some other hosting site like firebase

**Comment by israelmrios** [comment]
I had the same issue, and found it was the way I was Handling my Routing. I was using `<BrowserRouter>` on my root index.js file but GitHub Pages does not support browser history like your browser does. I switched my routing to `<HashRouter>` this type of router uses the hash portion of the URL to keep the UI in sync with the URL.

`ReactDOM.render(
  <React.StrictMode>
    <HashRouter>
      <App />
    </HashRouter>
  </React.StrictMode>,
  document.getElementById('root')
);`

**Comment by gitname** [comment]
Hi everyone, sorry about the long wait. In case you are still getting an HTTP 404 error page when you navigate to other URLs within your app, you may be running into a limitation of GitHub Pages, which (along with two available workarounds) is documented here: https://create-react-app.dev/docs/deployment/#notes-on-client-side-routing

I recently summarized the two workarounds here: https://github.com/gitname/react-gh-pages/issues/104#issuecomment-1203373499
