### ISSUE TITLE
Question: How can I push changes to the gh-pages branch

### ISSUE THREAD

**Issue by ansraika** [gitname/react-gh-pages#69]
Hi, I made some code changes to my master branch and pushed the same to the master branch. However my changes do not reflect in the website as the gh-pages still remains unchanged. How to make my changes reflect in gh-pages branch as well so that my website is updated

**Comment by gitname** [comment]
Hi @ansraika, did you run `$ npm run deploy` after you made the code changes? 

That command will run the `predeploy` and `deploy` scripts defined in `package.json`. 

The `predeploy` script builds a distributable instance of the React app and stores it in a folder named `build`; and the `deploy` script pushes the contents of that `build` folder up to the `gh-pages` branch.

**Comment by theeduardomora** [comment]
I followed the guide and was able to create a react app. However, I am not able to update my gh-pages branch (repo:https://github.com/theeduardomora/ImageClassifier/tree/gh-pages ).

 I made a code change to my package.json file and after running npm run deploy nothing seems to be being pushed to my gh-pages branch. I tried deleting .cache folder in node_modules aswell to see if that would fix anything but to no avail.

**Comment by theeduardomora** [comment]
I changed it while trying to fix this. I just deleted the repo and restarted the process again. You should be able to see the webpage now from https://theeduardomora.github.io/ImageClassifier/ , however it is empty and displays a console log error of 

Loading failed for the <script> with source “https://theeduardomora.github.io/static/js/main.6350fe01.js”

which I am currently trying to debug. A few other posts online I've seen about this just mentioned to include the homepage attribute but I already have this in my package.json file.

**Comment by theeduardomora** [comment]
Ah, can't believe I didn't notice that. It works now! Thank you so much.

**Comment by gitname** [comment]
Closing this issue since I didn't receive a reply from the OP after 6 months.
