### ISSUE TITLE
Change branch to gh-pages in setting

### ISSUE THREAD

**Issue by klaimyt** [gitname/react-gh-pages#76]
Hello! I have no time to do a pull request with additional instruction step, but I want to notify you about it.

Probably, because initially I tried to add my react project to github pages without gh-pages and only then I found your instruction and used gh-pages as deploy command I had an extra step. So, after using the deploy command in your local project, you need to open the project settings (on the github project repository page) and manually change the source branch on the pages tab, for example from main to the gh-pages branch.

I think it would be nice to add this as note to Step 7

**Comment by wasp0094** [comment]
can i open a pr referencing this?

**Comment by klaimyt** [comment]
> can i open a pr referencing this?

Yes :)
