### ISSUE TITLE
Restricted/Private Access to Source Code in main branch

### ISSUE THREAD

**Issue by ddppddpp** [gitname/react-gh-pages#81]
Thanks for the great instructions. Are you aware of a way to keep the source code in main with restricted access as opposed to what you suggest in step 8?

**Comment by gitname** [comment]
For **GitHub Free** users, the only type of repository that can be used with GitHub Pages is Public. In that situation, all the branches in the repo are public (i.e. anyone can read the `main` branch).

For **GitHub Pro** users (and other paying users), both Public and Private repositories can be used with GitHub Pages. In that situation, you can set the repo to be Private (i.e. so only you can see the `main` branch) while GitHub Pages still serves the content of the `gh-pages` branch.

**Comment by gitname** [comment]
A "hack" to the above is to have a Public repo that just has a `gh-pages` branch, and then a private repo that has the source code (e.g. in a `main` branch).

**Comment by gitname** [comment]
Hi @ddppddpp , I am closing this Issue because I think I answered your question via my two comments above. In case I haven't, you can still post additional comments once the Issue has been closed.

**Comment by ddppddpp** [comment]
Sorry, @gitname I was planning to respond sooner but life got in the way. Many thanks for the explanation. It was matching my understanding and current "hack" approach.

**Comment by gitname** [comment]
All good, @ddppddpp! Thanks for following up.

**Comment by ddppddpp** [comment]
To use the `hack` approach of keeping your code in a free private repo, but host GitHub pages in a free public repo, you can use the '-r' option when setting up your deploy script package.json:
`"deploy": "gh-pages -r https://github.com/<username>/<publicrepo> -b gh-pages -d build",`
