### ISSUE TITLE
Project properly deployed, however shows blank page when accessed

### ISSUE THREAD

**Issue by bickertonav** [gitname/react-gh-pages#88]
I recently deployed a repository ([linked here](https://github.com/bickertonav/kreyol-wordle/tree/gh-pages) and I noticed that, although it is deploying properly, when I attempt to access it it comes up as a blank page. I suspected it was an issue in my package.json, but I have no idea what it could be. Thank you guys in advance.

**Comment by gitname** [comment]
Hi @bickertonav , thanks for providing a link to the repository. 

I see the `package.json` file in that repository (i.e. https://github.com/bickertonav/kreyol-wordle/blob/main/package.json) contains the following `homepage` property:
```json
    "homepage": "https://roedoejet.github.io/AnyLanguage-Wordle",
```

When I visit that URL, I don't see a blank page; rather, I see a Wordle clone (screenshot below).

![image](https://user-images.githubusercontent.com/7143133/157375323-30e75d05-d123-4bb6-8c2b-8a86358a4067.png)

Is that the URL at which you saw a blank page?

**Comment by gitname** [comment]
The `gh-pages` branch in that repository doesn't look the way I expect. It looks to me like it contains the source code of your app; as opposed to the distributable version of your app. The distributable version would have been generated when you ran `$ npm run deploy`. In addition, it looks to me like the repository contains a React app that is different from the bare-bones one shown in the tutorial.

For the purpose of learning how you can deploy a React app to GitHub Pages, I recommend creating a temporary/throwaway repository and going through the tutorial once with that repository. That will leave you with a bare-bones, CRA-based React app deployed to GitHub Pages. Then, once you have successfully deployed that bare-bones app to GitHub Pages, I recommend you revisit the problematic repository (the one you linked to in your comment) and try to identify the ways that that repository differs from the repository of the app you were able to deploy.

**Comment by gitname** [comment]
Closing due to lack of reply.
