### ISSUE TITLE
Deployment deletes `CNAME` file from `gh-pages` branch (custom domain)

### ISSUE THREAD

**Issue by nimit2801** [gitname/react-gh-pages#89]
Every time I use `npm run deploy -- -m "Deploy React app to GitHub Pages"` from my main branch to deploy on `gh-pages` the it resets the custom URL and I've to make a new commit for CNAME to reset it to new the custom URL. Is there a solution for the same in `react-gh-pages`

Screen Shots
![image](https://user-images.githubusercontent.com/53462249/159016875-2bde11e0-9a51-4afa-aa4b-02e00d1adfc4.png)

Reference URL: https://github.com/Nuv-Yuva/nuvyuva 

Thank You

**Comment by TheoBong** [comment]
You can just put the CNAME file in your public folder.

**Comment by gitname** [comment]
Thanks, @TheoBong, for sharing a solution.

Hi @nimit2801, to elaborate on the solution shared by @TheoBong:

According to [the Create React App documentation about the `public` folder](https://create-react-app.dev/docs/using-the-public-folder): during the build process, files in the `public` folder will be copied as-is into the `build` folder. Running `$ npm run deploy` will then push the contents of that `build` folder to the remote `gh-pages` branch.

**Comment by nimit2801** [comment]
Can we add this in the documentation for the developers to know this beforehand @gitname?

**Comment by nimit2801** [comment]
> Thanks, @TheoBong, for sharing a solution.
> 
> Hi @nimit2801, to elaborate on the solution shared by @TheoBong:
> 
> According to [the Create React App documentation about the `public` folder](https://create-react-app.dev/docs/using-the-public-folder): during the build process, files in the `public` folder will be copied as-is into the `build` folder. Running `$ npm run deploy` will then push the contents of that `build` folder to the remote `gh-pages` branch.

Thank you for the explanation, it really helped!

**Comment by gitname** [comment]
> Can we add this in the documentation for the developers to know this beforehand @gitname?

Yes, thanks for suggesting that. For now, I'll add a link to this Issue, then eventually (once I have time to test it) spell it out in the instructions.

**Comment by carlosvega20** [comment]
you can elaborate something like this:
```
"scripts": {
    "deploy": "cp CNAME ./public/ && gh-pages -d public"
```

**Comment by alex-sherman** [comment]
# The correct solution

`gh-pages -d build --cname custom-domain.com`

**Comment by gitname** [comment]
Thanks for editing your comment.

**Comment by alex-sherman** [comment]
https://github.com/gitname/react-gh-pages/pull/217
