### ISSUE TITLE
ENOENT: no such file or directory, stat '/home/xxx/myproject/build'

### ISSUE THREAD

**Issue by xunwinds** [gitname/react-gh-pages#95]
```
> gh-pages -d build

ENOENT: no such file or directory, stat '/home/xxx/myproject/build'
```

**Comment by Abhaygajeepara** [comment]
@xunwinds  I'm encountering the same problem. Could you please share the solution that resolved the issue for you?

**Comment by gabriersdev** [comment]
> @xunwinds I'm encountering the same problem. Could you please share the solution that resolved the issue for you?

probably the name of the repository in which the files are saved after being built is not "build", but rather "dist", a pattern used by some frameworks or build platforms, such as Vite.

So, change the gh-pages deployment script according to the name of the repository where the built files are stored. If it is "dist", change it in `package.json`:

`"deploy": "gh-pages -d dist"`
